# Generated by Django 4.2.7 on 2024-10-29 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='picture', verbose_name='picture'),
            preserve_default=False,
        ),
    ]
