# Generated by Django 4.2.7 on 2024-12-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='carte_apprenant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='certificat_apprenant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(upload_to='picture/', verbose_name='picture'),
        ),
    ]
