# Generated by Django 4.2.7 on 2024-12-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_carte_apprenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(default='00000000000', max_length=20),
        ),
    ]
