# Generated by Django 4.2.7 on 2024-10-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(choices=[('promotion1', 'Promotion 1'), ('promotion2', 'Promotion 2'), ('promotion3', 'Promotion 3'), ('promotion4', 'Promotion 4')], max_length=50)),
                ('file', models.FileField(upload_to='album/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='formation/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
