# Generated by Django 4.2.7 on 2024-10-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_promotion_album_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='promotion',
            field=models.CharField(choices=[('promotion1', 'Promotion 1'), ('promotion2', 'Promotion 2'), ('promotion3', 'Promotion 3'), ('promotion4', 'Promotion 4')], max_length=50),
        ),
    ]
